#ifndef AEDIF_PREDEFINED_VAR_H_
#define AEDIF_PREDEFINED_VAR_H_

#include <lua.h>

#define AEDIF_LANGUAGE "__AEDIF_LANGUAGE__"
#define AEDIF_COMPILER "__AEDIF_COMPILER__"
#define AEDIF_STD "__AEDIF_STD__"
#define AEDIF_OPT_LEVEL "__AEDIF_OPT_LEVEL__"
#define AEDIF_WARNINGS "__AEDIF_WARNINGS__"
#define AEDIF_ERRORS "__AEDIF_ERRORS__"
#define AEDIF_FLAGS "__AEDIF_FLAGS__"

void predefineVars(lua_State* L);

#endif // AEDIF_PREDEFINED_VAR_H_
